//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iwaschenko_Palace.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volunteer
    {
        public int IdVolunteer { get; set; }
        public Nullable<int> IdMovement { get; set; }
        public Nullable<int> IdParticipation { get; set; }
        public Nullable<int> IdUsers { get; set; }
    
        public virtual Movemente Movemente { get; set; }
        public virtual Participation Participation { get; set; }
        public virtual User User { get; set; }
    }
}
