//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iwaschenko_Palace.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int IdWorkers { get; set; }
        public Nullable<int> IdDepartment { get; set; }
        public Nullable<int> IdPosition { get; set; }
        public Nullable<int> IdMovemente { get; set; }
        public Nullable<int> IdUsers { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
        public virtual Movemente Movemente { get; set; }
        public virtual Position Position { get; set; }
        public virtual User User { get; set; }
    }
}
